name: bolig_pipeline
version: '1.0.0'
config-version: 2

profile: bolig_pipeline

model-paths: ["models"]
test-paths: ["tests"]

models:
  bolig_pipeline:
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: table
